<?php
/**
 * THIS FILE IS AUTO-GENERATED BY LAZYRECORD,
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY.
 * 
 * Last Modified: March 30th at 12:34am
 */
namespace PM25\Model;


use LazyRecord;
use LazyRecord\Schema\RuntimeSchema;
use LazyRecord\Schema\Relationship;

class StationSchemaProxy extends RuntimeSchema
{

    public static $column_names = array (
  0 => 'country',
  1 => 'country_en',
  2 => 'city',
  3 => 'city_en',
  4 => 'county',
  5 => 'county_en',
  6 => 'province',
  7 => 'province_en',
  8 => 'name',
  9 => 'name_en',
  10 => 'address',
  11 => 'address_en',
  12 => 'area',
  13 => 'area_en',
  14 => 'longitude',
  15 => 'latitude',
  16 => 'rawdata',
  17 => 'location',
  18 => 'support_uv',
  19 => 'support_air',
  20 => 'remark',
  21 => 'code',
  22 => 'data_source',
  23 => 'id',
);
    public static $column_hash = array (
  'country' => 1,
  'country_en' => 1,
  'city' => 1,
  'city_en' => 1,
  'county' => 1,
  'county_en' => 1,
  'province' => 1,
  'province_en' => 1,
  'name' => 1,
  'name_en' => 1,
  'address' => 1,
  'address_en' => 1,
  'area' => 1,
  'area_en' => 1,
  'longitude' => 1,
  'latitude' => 1,
  'rawdata' => 1,
  'location' => 1,
  'support_uv' => 1,
  'support_air' => 1,
  'remark' => 1,
  'code' => 1,
  'data_source' => 1,
  'id' => 1,
);
    public static $mixin_classes = array (
);
    public static $column_names_include_virtual = array (
  0 => 'country',
  1 => 'country_en',
  2 => 'city',
  3 => 'city_en',
  4 => 'county',
  5 => 'county_en',
  6 => 'province',
  7 => 'province_en',
  8 => 'name',
  9 => 'name_en',
  10 => 'address',
  11 => 'address_en',
  12 => 'area',
  13 => 'area_en',
  14 => 'longitude',
  15 => 'latitude',
  16 => 'rawdata',
  17 => 'location',
  18 => 'support_uv',
  19 => 'support_air',
  20 => 'remark',
  21 => 'code',
  22 => 'data_source',
  23 => 'id',
);

        const schema_class = 'PM25\\Model\\StationSchema';
        const collection_class = 'PM25\\Model\\StationCollection';
        const model_class = 'PM25\\Model\\Station';
        const model_name = 'Station';
        const model_namespace = 'PM25\\Model';
        const primary_key = 'id';
        const table = 'stations';
        const label = 'Station';

    public function __construct()
    {
        /** columns might have closure, so it can not be const */
        $this->columnData      = array( 
  'country' => array( 
      'name' => 'country',
      'attributes' => array( 
          'type' => 'varchar(30)',
          'isa' => 'str',
          'size' => 30,
        ),
    ),
  'country_en' => array( 
      'name' => 'country_en',
      'attributes' => array( 
          'type' => 'varchar(60)',
          'isa' => 'str',
          'size' => 60,
        ),
    ),
  'city' => array( 
      'name' => 'city',
      'attributes' => array( 
          'type' => 'varchar(30)',
          'isa' => 'str',
          'size' => 30,
        ),
    ),
  'city_en' => array( 
      'name' => 'city_en',
      'attributes' => array( 
          'type' => 'varchar(60)',
          'isa' => 'str',
          'size' => 60,
        ),
    ),
  'county' => array( 
      'name' => 'county',
      'attributes' => array( 
          'type' => 'varchar(30)',
          'isa' => 'str',
          'size' => 30,
        ),
    ),
  'county_en' => array( 
      'name' => 'county_en',
      'attributes' => array( 
          'type' => 'varchar(60)',
          'isa' => 'str',
          'size' => 60,
        ),
    ),
  'province' => array( 
      'name' => 'province',
      'attributes' => array( 
          'type' => 'varchar(60)',
          'isa' => 'str',
          'size' => 60,
        ),
    ),
  'province_en' => array( 
      'name' => 'province_en',
      'attributes' => array( 
          'type' => 'varchar(60)',
          'isa' => 'str',
          'size' => 60,
        ),
    ),
  'name' => array( 
      'name' => 'name',
      'attributes' => array( 
          'type' => 'varchar(30)',
          'isa' => 'str',
          'size' => 30,
        ),
    ),
  'name_en' => array( 
      'name' => 'name_en',
      'attributes' => array( 
          'type' => 'varchar(60)',
          'isa' => 'str',
          'size' => 60,
        ),
    ),
  'address' => array( 
      'name' => 'address',
      'attributes' => array( 
          'type' => 'varchar(60)',
          'isa' => 'str',
          'size' => 60,
        ),
    ),
  'address_en' => array( 
      'name' => 'address_en',
      'attributes' => array( 
          'type' => 'varchar(120)',
          'isa' => 'str',
          'size' => 120,
        ),
    ),
  'area' => array( 
      'name' => 'area',
      'attributes' => array( 
          'type' => 'varchar(30)',
          'isa' => 'str',
          'size' => 30,
        ),
    ),
  'area_en' => array( 
      'name' => 'area_en',
      'attributes' => array( 
          'type' => 'varchar(60)',
          'isa' => 'str',
          'size' => 60,
        ),
    ),
  'longitude' => array( 
      'name' => 'longitude',
      'attributes' => array( 
          'type' => 'double',
          'isa' => 'double',
        ),
    ),
  'latitude' => array( 
      'name' => 'latitude',
      'attributes' => array( 
          'type' => 'double',
          'isa' => 'double',
        ),
    ),
  'rawdata' => array( 
      'name' => 'rawdata',
      'attributes' => array( 
          'type' => 'text',
          'isa' => 'str',
        ),
    ),
  'location' => array( 
      'name' => 'location',
      'attributes' => array( 
          'type' => 'point',
          'isa' => 'str',
        ),
    ),
  'support_uv' => array( 
      'name' => 'support_uv',
      'attributes' => array( 
          'type' => 'boolean',
          'isa' => 'bool',
        ),
    ),
  'support_air' => array( 
      'name' => 'support_air',
      'attributes' => array( 
          'type' => 'boolean',
          'isa' => 'bool',
        ),
    ),
  'remark' => array( 
      'name' => 'remark',
      'attributes' => array( 
          'type' => 'text',
          'isa' => 'str',
        ),
    ),
  'code' => array( 
      'name' => 'code',
      'attributes' => array( 
          'type' => 'varchar(32)',
          'isa' => 'str',
          'size' => 32,
        ),
    ),
  'data_source' => array( 
      'name' => 'data_source',
      'attributes' => array( 
          'type' => 'varchar(64)',
          'isa' => 'str',
          'size' => 64,
        ),
    ),
  'id' => array( 
      'name' => 'id',
      'attributes' => array( 
          'type' => 'integer',
          'isa' => 'int',
          'primary' => true,
          'autoIncrement' => true,
        ),
    ),
);
        $this->columnNames     = array( 
  'id',
  'country',
  'country_en',
  'city',
  'city_en',
  'county',
  'county_en',
  'province',
  'province_en',
  'name',
  'name_en',
  'address',
  'address_en',
  'area',
  'area_en',
  'longitude',
  'latitude',
  'rawdata',
  'location',
  'support_uv',
  'support_air',
  'remark',
  'code',
  'data_source',
);
        $this->primaryKey      = 'id';
        $this->table           = 'stations';
        $this->modelClass      = 'PM25\\Model\\Station';
        $this->collectionClass = 'PM25\\Model\\StationCollection';
        $this->label           = 'Station';
        $this->relations       = array( 
  'station_measure_attributes' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 2,
      'self_column' => 'id',
      'self_schema' => 'PM25\\Model\\StationSchema',
      'foreign_column' => 'station_id',
      'foreign_schema' => 'PM25\\Model\\StationMeasureAttributeSchema',
    ),
)),
  'measure_attributes' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 3,
      'relation_junction' => 'station_measure_attributes',
      'relation_foreign' => 'attribute',
    ),
)),
  'measurements' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 2,
      'self_column' => 'id',
      'self_schema' => 'PM25\\Model\\StationSchema',
      'foreign_column' => 'station_id',
      'foreign_schema' => 'PM25\\Model\\MeasureSchema',
      'order' => array( 
          array( 
              'published_at',
              'DESC',
            ),
        ),
    ),
)),
);
        $this->readSourceId    = 'default';
        $this->writeSourceId    = 'default';
        parent::__construct();
    }


    /**
     * Code block for message id parser.
     */
    private function __() {
        _('Station');
    }

}
