<?php
/**
 * THIS FILE IS AUTO-GENERATED BY LAZYRECORD,
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY.
 * 
 * Last Modified: March 10th at 3:00pm
 */
namespace PM25\Model;


use LazyRecord;
use LazyRecord\Schema\RuntimeSchema;
use LazyRecord\Schema\Relationship;

class StationSchemaProxy extends RuntimeSchema
{

    public static $column_names = array (
  0 => 'country',
  1 => 'country_en',
  2 => 'city',
  3 => 'city_en',
  4 => 'name',
  5 => 'name_en',
  6 => 'address',
  7 => 'address_en',
  8 => 'longitude',
  9 => 'latitude',
  10 => 'id',
);
    public static $column_hash = array (
  'country' => 1,
  'country_en' => 1,
  'city' => 1,
  'city_en' => 1,
  'name' => 1,
  'name_en' => 1,
  'address' => 1,
  'address_en' => 1,
  'longitude' => 1,
  'latitude' => 1,
  'id' => 1,
);
    public static $mixin_classes = array (
);
    public static $column_names_include_virtual = array (
  0 => 'country',
  1 => 'country_en',
  2 => 'city',
  3 => 'city_en',
  4 => 'name',
  5 => 'name_en',
  6 => 'address',
  7 => 'address_en',
  8 => 'longitude',
  9 => 'latitude',
  10 => 'id',
);

        const schema_class = 'PM25\\Model\\StationSchema';
        const collection_class = 'PM25\\Model\\StationCollection';
        const model_class = 'PM25\\Model\\Station';
        const model_name = 'Station';
        const model_namespace = 'PM25\\Model';
        const primary_key = 'id';
        const table = 'stations';
        const label = 'Station';

    public function __construct()
    {
        /** columns might have closure, so it can not be const */
        $this->columnData      = array( 
  'country' => array( 
      'name' => 'country',
      'attributes' => array( 
          'type' => 'varchar(30)',
          'isa' => 'str',
          'size' => 30,
        ),
    ),
  'country_en' => array( 
      'name' => 'country_en',
      'attributes' => array( 
          'type' => 'varchar(30)',
          'isa' => 'str',
          'size' => 30,
        ),
    ),
  'city' => array( 
      'name' => 'city',
      'attributes' => array( 
          'type' => 'varchar(30)',
          'isa' => 'str',
          'size' => 30,
        ),
    ),
  'city_en' => array( 
      'name' => 'city_en',
      'attributes' => array( 
          'type' => 'varchar(30)',
          'isa' => 'str',
          'size' => 30,
        ),
    ),
  'name' => array( 
      'name' => 'name',
      'attributes' => array( 
          'type' => 'varchar(30)',
          'isa' => 'str',
          'size' => 30,
        ),
    ),
  'name_en' => array( 
      'name' => 'name_en',
      'attributes' => array( 
          'type' => 'varchar(60)',
          'isa' => 'str',
          'size' => 60,
        ),
    ),
  'address' => array( 
      'name' => 'address',
      'attributes' => array( 
          'type' => 'varchar(60)',
          'isa' => 'str',
          'size' => 60,
        ),
    ),
  'address_en' => array( 
      'name' => 'address_en',
      'attributes' => array( 
          'type' => 'varchar(60)',
          'isa' => 'str',
          'size' => 60,
        ),
    ),
  'longitude' => array( 
      'name' => 'longitude',
      'attributes' => array( 
          'type' => 'double',
          'isa' => 'double',
        ),
    ),
  'latitude' => array( 
      'name' => 'latitude',
      'attributes' => array( 
          'type' => 'double',
          'isa' => 'double',
        ),
    ),
  'id' => array( 
      'name' => 'id',
      'attributes' => array( 
          'type' => 'integer',
          'isa' => 'int',
          'primary' => true,
          'autoIncrement' => true,
        ),
    ),
);
        $this->columnNames     = array( 
  'id',
  'country',
  'country_en',
  'city',
  'city_en',
  'name',
  'name_en',
  'address',
  'address_en',
  'longitude',
  'latitude',
);
        $this->primaryKey      = 'id';
        $this->table           = 'stations';
        $this->modelClass      = 'PM25\\Model\\Station';
        $this->collectionClass = 'PM25\\Model\\StationCollection';
        $this->label           = 'Station';
        $this->relations       = array( 
);
        $this->readSourceId    = 'default';
        $this->writeSourceId    = 'default';
        parent::__construct();
    }


    /**
     * Code block for message id parser.
     */
    private function __() {
        _('Station');
    }

}
